# yaml-language-server: $schema=../schemas/dashboard.schema.yml
id: atucha
title: Atucha
pages:
- id: shortTerm
  pageType: serieObsConSim 
  title: Pronóstico a Corto Plazo
  icon: short-term.png
  iconWidth: 120
  iconHeight: 75
  itemIcon: KeyboardArrowRightIcon
  type: puntual
  seriesIdObs: 151
  nombre_estacion: Atucha
  calId: 489
  seriesIdSim: 3403
  mainQualifier: main
  errorBandLow: error_band_01
  errorBandHigh: error_band_99
  timeStartDays: 7
  refLines:
    bottom: 0.5
    low: 0.8
    up: 4.0
    top: 5.1
- id: longTerm
  pageType: serieObsConSim 
  title: Pronóstico a Largo Plazo
  icon: long-term.png
  iconWidth: 225
  iconHeight: 75
  itemIcon: KeyboardDoubleArrowRightIcon
  type: puntual
  seriesIdObs: 36030
  nombre_estacion: Atucha
  calId: 499
  seriesIdSim: 35472
  timeStartDays: 60
  refLines:
    bottom: 0.5
    low: 0.8
    up: 4.0
    top: 5.1
  mainQualifier: main
  errorBandLow: p10
  errorBandHigh: p90
- id: meteo
  pageType: serieObsConSim 
  title: Pronóstico Meteorológico del Río de la Plata
  icon: meteorological.png
  itemIcon: WeatherWindyIcon
  iconWidth: 90
  iconHeight: 75
  type: puntual
  seriesIdObs: 52
  nombre_estacion: San Fernando
  calId: 432
  seriesIdSim: 26202
  mainQualifier: main
  errorBandLow: p05
  errorBandHigh: p95
  timeStartDays: 7
  viento:
    title: Velocidad y dirección del viento en estación Pilote Norden
    image: https://alerta.ina.gob.ar/ina/51-GEFS_WAVE/gefs_wave/gefs.wave.last.gif
    estacionId: 1740
    seriesIdWindVel: 35478
    seriesIdWindDir: 35479
# - id: meteo
#   pageType: meteorological
#   icon: meteorological.png
#   iconWidth: 90
#   iconHeight: 75
#   title: Pronóstico Meteorológico
