id: corrientes
pages:
- id: shortTerm
  pageType: serieObsConSim 
  title: Pronóstico a Corto Plazo
  icon: short-term.png
  iconWidth: 120
  iconHeight: 75
  itemIcon: KeyboardArrowRightIcon
  type: puntual
  seriesIdObs: 26261
  nombre_estacion: Corrientes
  calId: 289
  seriesIdSim: 1540
  mainQualifier: medio
  errorBandLow: inferior
  errorBandHigh: superior
  timeStartDays: 30
  seriesAuxiliares:
  - tipo: puntual
    series_id: 26257
  - tipo: puntual
    series_id: 26690
